const products=[{id:'AD-HOLO-A6',name:'Adesivo holográfico A6',price:.78,minDays:3,materials:[['Vinil holográfico',.018,'m²'],['Laminação',.018,'m²']],route:[['Pré-impressão',15],['Impressão',35],['Laminação',25],['Recorte',40],['Acabamento',25]]},{id:'PRINT-A5',name:'Print A5 250g',price:2.4,minDays:2,materials:[['Papel couchê 250g',1,'fl'],['Tinta',.006,'un']],route:[['Pré-impressão',10],['Impressão',30],['Corte',20],['Conferência',15]]},{id:'KEY-ACR',name:'Chaveiro acrílico',price:5.9,minDays:5,materials:[['Acrílico 3mm',.008,'m²'],['Argola',1,'un']],route:[['Arte',20],['Impressão',30],['Corte laser',55],['Montagem',45],['Conferência',20]]}];
const orders=[
{id:'#1048',client:'Luna Papelaria',due:'25 ago',month:'ago',status:'Produção',items:[{product:'Adesivo holográfico A6',qty:250,done:110,waste:4,status:'Impressão'},{product:'Print A5 250g',qty:80,done:80,waste:2,status:'Acabamento'},{product:'Chaveiro acrílico',qty:35,done:0,waste:0,status:'Corte'}]},
{id:'#1047',client:'Mimo & Co.',due:'29 ago',month:'ago',status:'Produção',items:[{product:'Print A5 250g',qty:180,done:95,waste:3,status:'Impressão'},{product:'Adesivo holográfico A6',qty:300,done:0,waste:0,status:'Laminação'}]},
{id:'#1046',client:'Clara Studio',due:'04 set',month:'set',status:'Preparação',items:[{product:'Chaveiro acrílico',qty:120,done:40,waste:3,status:'Corte'},{product:'Print A5 250g',qty:60,done:0,waste:0,status:'Arte aprovada'}]},
{id:'#1045',client:'Ateliê Nuvem',due:'12 set',month:'set',status:'Preparação',items:[{product:'Adesivo holográfico A6',qty:400,done:0,waste:0,status:'Arte aprovada'},{product:'Chaveiro acrílico',qty:50,done:0,waste:0,status:'Arte aprovada'}]},
{id:'#1044',client:'Mori Shop',due:'22 set',month:'set',status:'Entrada',items:[{product:'Print A5 250g',qty:260,done:0,waste:0,status:'Aguardando arte'},{product:'Adesivo holográfico A6',qty:500,done:0,waste:0,status:'Aguardando arte'},{product:'Chaveiro acrílico',qty:90,done:0,waste:0,status:'Aguardando arte'}]},
{id:'#1043',client:'Casa Lótus',due:'30 set',month:'set',status:'Entrada',items:[{product:'Adesivo holográfico A6',qty:700,done:0,waste:0,status:'Confirmado'},{product:'Print A5 250g',qty:320,done:0,waste:0,status:'Confirmado'}]}
];
const materials=[{name:'Vinil holográfico',stock:28.8,reserved:21.4,unit:'m²',min:5},{name:'Papel couchê 250g',stock:1620,reserved:1110,unit:'folhas',min:250},{name:'Acrílico 3mm',stock:8.1,reserved:5.3,unit:'m²',min:1.5},{name:'Laminação brilho',stock:32.5,reserved:24.8,unit:'m²',min:4},{name:'Argolas chaveiro',stock:740,reserved:480,unit:'un',min:150},{name:'Tinta magenta',stock:62,reserved:38,unit:'%',min:20}];
const jobs=[['08:00','Pré-impressão','#1048 · item 1 · Luna Papelaria','Concluído'],['09:00','Impressão','#1048 · adesivos · 250 un','Produzindo'],['10:20','Corte','#1046 · chaveiros · 120 un','Próximo'],['13:30','Acabamento','#1048 · prints · 80 un','Agendado'],['15:10','Laminação','#1047 · adesivos · 300 un','Agendado']];
const scheduleWeeks=[
{label:'17–23 ago',month:'AGOSTO',load:92,jobs:{'Pré-impressão':['#1048 · Luna','#1047 · Mimo'],'Impressão':['#1048 · Adesivos','#1047 · Prints'],'Laminação / Corte':['#1046 · Chaveiros'],'Acabamento':['#1048 · Prints']}},
{label:'24–30 ago',month:'AGOSTO',load:96,jobs:{'Pré-impressão':['#1046 · Clara'],'Impressão':['#1047 · Adesivos','#1046 · Prints'],'Laminação / Corte':['#1047 · Adesivos','#1046 · Chaveiros'],'Acabamento':['#1048 · fechamento','#1047 · parcial']}},
{label:'31 ago–06 set',month:'SETEMBRO',load:88,jobs:{'Pré-impressão':['#1045 · Ateliê'],'Impressão':['#1046 · Prints','#1045 · Adesivos'],'Laminação / Corte':['#1045 · Adesivos'],'Acabamento':['#1046 · entrega 04/set']}},
{label:'07–13 set',month:'SETEMBRO',load:83,jobs:{'Pré-impressão':['#1044 · Mori'],'Impressão':['#1045 · Adesivos','#1045 · Chaveiros'],'Laminação / Corte':['#1045 · Chaveiros'],'Acabamento':['#1045 · entrega 12/set']}},
{label:'14–20 set',month:'SETEMBRO',load:78,jobs:{'Pré-impressão':['#1043 · Casa Lótus'],'Impressão':['#1044 · Prints','#1044 · Adesivos'],'Laminação / Corte':['#1044 · Chaveiros','#1044 · Adesivos'],'Acabamento':['#1044 · parcial']}},
{label:'21–27 set',month:'SETEMBRO',load:71,jobs:{'Pré-impressão':['janela novos pedidos'],'Impressão':['#1043 · Adesivos','#1043 · Prints'],'Laminação / Corte':['#1043 · Adesivos'],'Acabamento':['#1044 · entrega 22/set']}},
{label:'28–30 set',month:'SETEMBRO',load:54,jobs:{'Pré-impressão':['janela disponível'],'Impressão':['buffer'],'Laminação / Corte':['buffer'],'Acabamento':['#1043 · entrega 30/set']}}
];
function el(id){return document.getElementById(id)}
function itemSummary(o){return o.items.map(i=>`${i.qty}× ${i.product}`).join(' · ')}
function totals(o){return o.items.reduce((a,i)=>({qty:a.qty+i.qty,done:a.done+i.done,waste:a.waste+i.waste}),{qty:0,done:0,waste:0})}
function render(){el('todayTimeline').innerHTML=jobs.map(j=>`<div class="timeline-item"><time>${j[0]}</time><i class="dot"></i><div class="info"><b>${j[1]}</b><small>${j[2]}</small></div><span class="status">${j[3]}</span></div>`).join('');el('materialList').innerHTML=materials.slice(0,4).map(m=>{let free=m.stock-m.reserved,p=Math.max(8,Math.min(100,free/m.stock*100));return `<div class="material"><div class="material-top"><b>${m.name}</b><span>${free.toFixed(1)} ${m.unit} livres</span></div><small>${m.reserved} ${m.unit} reservados até setembro</small><div class="bar"><i style="width:${p}%"></i></div></div>`}).join('');el('orderTable').innerHTML=`<div class="order-row header"><span>PEDIDO</span><span>ITENS</span><span>STATUS</span><span>PRODUÇÃO</span><span>PRAZO</span></div>`+orders.map(o=>{const t=totals(o);return `<div class="order-row"><div><b>${o.id}</b><small>${o.client}</small></div><div><b>${o.items.length} produtos</b><small>${itemSummary(o)}</small></div><span class="status">${o.status}</span><span>${t.done}/${t.qty}<small>${t.waste} perdas totais</small></span><b>${o.due}</b></div>`}).join('');renderKanban();renderStock();renderProducts();renderSchedule();setupQuote();setupOrderItems()}
function renderKanban(){const groups=['Entrada','Preparação','Produção','Finalização'];el('ordersBoard').innerHTML=groups.map(g=>`<div class="kanban-col"><h3>${g} · ${orders.filter(o=>o.status===g).length}</h3>${orders.filter(o=>o.status===g).map(o=>`<article class="ticket"><b>${o.id} · ${o.client}</b><p><strong>${o.items.length} itens</strong><br>${o.items.map(i=>`${i.qty}× ${i.product} — ${i.status}`).join('<br>')}</p><div class="ticket-meta"><span>${o.month==='set'?'Planejado em setembro':'Em agosto'}</span><b>${o.due}</b></div></article>`).join('')}</div>`).join('')}
function renderStock(){el('stockGrid').innerHTML=materials.map(m=>{let free=m.stock-m.reserved,low=free<m.min;return `<article class="stock-card"><span class="tag">${low?'REPOR EM BREVE':'ESTOQUE OK'}</span><strong>${m.name}</strong><p>${low?'Saldo livre abaixo da margem mínima para o horizonte planejado.':'Saldo considerando reservas de agosto e setembro.'}</p><div class="stock-numbers"><span>Total <b>${m.stock} ${m.unit}</b></span><span>Reservado <b>${m.reserved}</b></span><span>Livre <b>${free.toFixed(1)}</b></span></div></article>`}).join('')}
function renderProducts(){el('productGrid').innerHTML=products.map(p=>`<article class="product-card"><span class="tag">${p.id}</span><strong>${p.name}</strong><p>R$ ${p.price.toFixed(2).replace('.',',')} / un · lead time base ${p.minDays} dias</p><div class="route">${p.route.map(r=>`<span>${r[0]} · ${r[1]}min</span>`).join('')}</div><p><b>Materiais:</b> ${p.materials.map(m=>m[0]).join(', ')}</p></article>`).join('')}
function renderSchedule(){const processes=['Pré-impressão','Impressão','Laminação / Corte','Acabamento'];el('capacitySummary').innerHTML=scheduleWeeks.map(w=>`<div class="capacity-week"><span>${w.label}</span><b>${w.load}%</b><div class="bar"><i style="width:${w.load}%"></i></div><small>${w.month}</small></div>`).join('');el('productionGrid').innerHTML=`<div class="process-row long"><div class="process-name sticky-name">PROCESSO</div>${scheduleWeeks.map(w=>`<div class="week-head"><b>${w.label}</b><small>${w.month} · ${w.load}% ocupado</small></div>`).join('')}</div>`+processes.map((p,pi)=>`<div class="process-row long"><div class="process-name sticky-name">${p}</div>${scheduleWeeks.map((w,wi)=>`<div class="day week-cell">${(w.jobs[p]||[]).map(j=>`<div class="job ${wi<2?'current':'future-job'} ${j==='buffer'?'buffer-job':''}">${j}</div>`).join('')}${!(w.jobs[p]||[]).length?'<small>capacidade livre</small>':''}</div>`).join('')}</div>`).join('')}
function setupQuote(){el('quoteProduct').innerHTML=products.map((p,i)=>`<option value="${i}">${p.name}</option>`).join('');el('quoteResult').innerHTML='<div><div style="font-size:36px">♡</div><b>Simule uma encomenda</b><p>O prazo considera uma agenda que já possui clientes até o fim de setembro.</p></div>';el('calcQuote').onclick=()=>{const p=products[+el('quoteProduct').value],q=Math.max(1,+el('quoteQty').value||1),subtotal=p.price*q,date=new Date(2026,8,30);date.setDate(date.getDate()+p.minDays+Math.ceil(p.minDays*.25));const desired=el('quoteDate').value?new Date(el('quoteDate').value+'T12:00:00'):null,valid=!desired||desired>=date;el('quoteResult').innerHTML=`<div><span class="tag">COTAÇÃO ESTIMADA</span><div class="price">R$ ${subtotal.toFixed(2).replace('.',',')}</div><p>${q} × ${p.name}</p><p><b>Primeira entrega segura estimada:</b> ${date.toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})}<br><small>Após a capacidade já reservada + roteiro + margem de segurança.</small></p>${desired?`<span class="status">${valid?'Data solicitada viável':'Data anterior à capacidade simulada'}</span>`:''}</div>`}}
let orderItemCount=0;function addOrderItem(){orderItemCount++;const row=document.createElement('div');row.className='order-item-editor';row.innerHTML=`<div class="item-number">${orderItemCount}</div><label>Produto<select>${products.map(p=>`<option>${p.name}</option>`).join('')}</select></label><label>Quantidade<input type="number" min="1" value="100"></label><label>Observação / arte<input placeholder="Variação, acabamento, referência..."></label><button type="button" class="remove-item">×</button><div class="item-attachment">♡ Anexos e comentários pertencem a este item</div>`;row.querySelector('.remove-item').onclick=()=>row.remove();el('orderItems').appendChild(row)}
function setupOrderItems(){el('orderItems').innerHTML='';orderItemCount=0;addOrderItem();addOrderItem();el('addOrderItem').onclick=addOrderItem}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>switchView(b.dataset.view));function switchView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));el(id).classList.add('active-view');document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));window.scrollTo(0,0)}
const dlg=el('orderDialog');['newOrder','newOrder2'].forEach(id=>el(id)?.addEventListener('click',()=>{setupOrderItems();dlg.showModal()}));render();