(()=>{
 const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 const uid=p=>p+Math.random().toString(36).slice(2,8);
 const base=window.BennieManagement||{materials:[],machines:[],products:[]};
 const state={materials:base.materials||[],resources:[
   ...(base.machines||[]).map(m=>({id:m.id,name:m.name,type:'equipment',process:m.process||'Produção',minutesDay:480,wear:1,returnMin:10})),
   {id:'manual-files',name:'Preparo de arquivos',type:'manual',process:'Pré-produção',minutesDay:480,wear:0,returnMin:0},
   {id:'manual-box',name:'Preparo da caixa',type:'manual',process:'Expedição',minutesDay:480,wear:0,returnMin:0},
   {id:'manual-qc',name:'Revisão de qualidade',type:'manual',process:'Qualidade',minutesDay:480,wear:0,returnMin:0}
 ],products:[]};
 function seed(){
   const src=(base.products?.length?base.products:(window.products||[]));
   state.products=src.map((p,i)=>({id:p.id||`P${i+1}`,name:p.name,image:p.image||'',description:p.description||'',price:+p.price||0,bom:(p.bom||[]).map(b=>({material:b.material,qty:+b.qty||0})),operations:(p.operations||p.route||[]).map((r,n)=>Array.isArray(r)?{id:uid('op'),name:r[0],resource:findResource(r[1],r[0]),setupMin:n===0?10:5,runMin:+r[2]||15,batchQty:100}:{...r})}))
 }
 function findResource(resourceName,process){const r=state.resources.find(x=>x.name===resourceName||x.process===process);return r?.id||'manual-files'}
 seed();
 const material=id=>state.materials.find(x=>x.id===id);
 const resource=id=>state.resources.find(x=>x.id===id);
 const product=id=>state.products.find(x=>x.id===id)||state.products.find(x=>x.name===id);
 const options=(arr,sel,label='name')=>arr.map(x=>`<option value="${x.id}" ${x.id===sel?'selected':''}>${x[label]}</option>`).join('');
 const unitMaterialCost=p=>(p.bom||[]).reduce((s,b)=>s+(material(b.material)?.cost||0)*(+b.qty||0),0);
 function operationMinutes(op,qty){const batches=Math.max(1,Math.ceil(qty/Math.max(1,+op.batchQty||1)));return (+op.setupMin||0)+(+op.runMin||0)*batches}
 function productMinutes(p,qty){return (p.operations||[]).reduce((s,op)=>s+operationMinutes(op,qty),0)}
 function ensureDialogs(){
  if(document.getElementById('entityDialog'))return;
  const d=document.createElement('dialog');d.id='entityDialog';d.innerHTML='<form method="dialog" class="modal technical-dialog"><div class="modal-head"><div><span class="tag" id="entityTag">CADASTRO</span><h2 id="entityTitle">Novo</h2></div><button value="cancel" class="close">×</button></div><div id="entityBody"></div><div class="modal-actions"><button value="cancel" class="ghost2">Cancelar</button><button type="button" id="entitySave" class="primary">Salvar</button></div></form>';document.body.appendChild(d)
 }
 function openMaterial(){ensureDialogs();const d=document.getElementById('entityDialog');document.getElementById('entityTag').textContent='MATÉRIA-PRIMA';document.getElementById('entityTitle').textContent='Cadastrar matéria-prima';document.getElementById('entityBody').innerHTML=`<div class="form-grid"><label>Nome<input id="mName" placeholder="Ex.: Vinil branco"></label><label>Unidade<input id="mUnit" placeholder="m², folha, un"></label><label>Estoque atual<input id="mStock" type="number" step="0.01" value="0"></label><label>Estoque mínimo<input id="mMin" type="number" step="0.01" value="0"></label><label>Custo unitário<input id="mCost" type="number" step="0.01" value="0"></label></div>`;document.getElementById('entitySave').onclick=()=>{state.materials.push({id:uid('mat'),name:val('mName','Nova matéria'),unit:val('mUnit','un'),stock:num('mStock'),min:num('mMin'),cost:num('mCost')});d.close();renderCatalog()};d.showModal()}
 function openResource(){ensureDialogs();const d=document.getElementById('entityDialog');document.getElementById('entityTag').textContent='RECURSO';document.getElementById('entityTitle').textContent='Cadastrar equipamento ou etapa manual';document.getElementById('entityBody').innerHTML=`<div class="form-grid"><label>Nome<input id="rName" placeholder="Ex.: Plotter 01 / Revisão visual"></label><label>Tipo<select id="rType"><option value="equipment">Equipamento</option><option value="manual">Manual</option></select></label><label>Processo<input id="rProcess" placeholder="Impressão, Corte, Qualidade..."></label><label>Minutos disponíveis/dia<input id="rDay" type="number" value="480"></label><label>Desgaste por hora (%)<input id="rWear" type="number" step="0.1" value="0"></label><label>Tempo de retorno/setup após uso (min)<input id="rReturn" type="number" value="0"></label></div>`;document.getElementById('entitySave').onclick=()=>{state.resources.push({id:uid('res'),name:val('rName','Novo recurso'),type:val('rType','manual'),process:val('rProcess','Produção'),minutesDay:num('rDay',480),wear:num('rWear'),returnMin:num('rReturn')});d.close();renderCatalog()};d.showModal()}
 function productForm(){return `<div class="form-grid"><label>Código<input id="pCode" placeholder="PROD-001"></label><label>Nome<input id="pName" placeholder="Nome do produto"></label><label>Preço de venda<input id="pPrice" type="number" step="0.01" value="0"></label><label>Imagem<input id="pImage" type="file" accept="image/*"></label></div><label>Descrição<textarea id="pDesc" rows="2"></textarea></label><div class="builder-section"><div class="builder-head"><div><span class="tag">MATERIAIS</span><b>BOM de consumo</b></div><button type="button" class="ghost2" id="addBomLine">＋ material</button></div><div id="newBomLines"></div></div><div class="builder-section"><div class="builder-head"><div><span class="tag">OPERAÇÕES</span><b>Roteiro e tempos</b></div><button type="button" class="ghost2" id="addOpLine">＋ operação</button></div><div id="newOpLines"></div><small class="builder-note">Use recurso manual para preparo de arquivos, preparo da caixa e revisão de qualidade. O tempo dessas etapas entra na capacidade e no prazo.</small></div>`}
 function addBomLine(root,materialId=state.materials[0]?.id,qty=1){root.insertAdjacentHTML('beforeend',`<div class="bom-builder-line"><select data-new-mat>${options(state.materials,materialId)}</select><input data-new-qty type="number" step="0.001" value="${qty}" placeholder="Consumo/un"><button type="button" class="ghost2" data-remove-line>×</button></div>`);root.lastElementChild.querySelector('[data-remove-line]').onclick=()=>root.lastElementChild?.remove()}
 function addOpLine(root,op={}){const rid=op.resource||state.resources[0]?.id;root.insertAdjacentHTML('beforeend',`<div class="op-builder-line"><input data-op-name value="${op.name||''}" placeholder="Etapa: imprimir, cortar, revisar..."><select data-op-resource>${options(state.resources,rid)}</select><label>Prep. min<input data-op-setup type="number" value="${op.setupMin??5}"></label><label>Tempo/lote<input data-op-run type="number" value="${op.runMin??15}"></label><label>Qtd. lote<input data-op-batch type="number" value="${op.batchQty??100}"></label><button type="button" class="ghost2" data-remove-line>×</button></div>`);root.lastElementChild.querySelector('[data-remove-line]').onclick=e=>e.currentTarget.parentElement.remove()}
 function openProduct(){ensureDialogs();const d=document.getElementById('entityDialog');document.getElementById('entityTag').textContent='PRODUTO + BOM';document.getElementById('entityTitle').textContent='Cadastrar produto';document.getElementById('entityBody').innerHTML=productForm();const br=document.getElementById('newBomLines'),or=document.getElementById('newOpLines');addBomLine(br);addOpLine(or,{name:'Preparo de arquivos',resource:'manual-files',setupMin:5,runMin:10,batchQty:1});document.getElementById('addBomLine').onclick=()=>addBomLine(br);document.getElementById('addOpLine').onclick=()=>addOpLine(or);let image='';document.getElementById('pImage').onchange=e=>{const f=e.target.files?.[0];if(f)image=URL.createObjectURL(f)};document.getElementById('entitySave').onclick=()=>{const p={id:val('pCode',`P${state.products.length+1}`),name:val('pName','Novo produto'),price:num('pPrice'),description:val('pDesc',''),image:image||state.products[0]?.image||'',bom:[...br.children].map(r=>({material:r.querySelector('[data-new-mat]').value,qty:+r.querySelector('[data-new-qty]').value||0})),operations:[...or.children].map(r=>({id:uid('op'),name:r.querySelector('[data-op-name]').value||'Operação',resource:r.querySelector('[data-op-resource]').value,setupMin:+r.querySelector('[data-op-setup]').value||0,runMin:+r.querySelector('[data-op-run]').value||0,batchQty:+r.querySelector('[data-op-batch]').value||1}))};state.products.push(p);d.close();renderCatalog();refreshClientProducts()};d.showModal()}
 function val(id,f=''){return document.getElementById(id)?.value?.trim()||f} function num(id,f=0){const v=+document.getElementById(id)?.value;return Number.isFinite(v)?v:f}
 function renderCatalog(){const bom=document.getElementById('bomBuilder'),mats=document.getElementById('materialsAdmin'),res=document.getElementById('machinesAdmin');if(!bom)return;bom.innerHTML=`<div class="management-grid">${state.products.map(p=>`<article class="manage-card product-manage"><img src="${p.image}" alt=""><div><span class="tag">${p.id}</span><h3>${p.name}</h3><p>${p.description}</p><div class="price-line"><span>Custo material <b>${money(unitMaterialCost(p))}</b></span><span>Venda <b>${money(p.price)}</b></span></div><h4>Materiais</h4>${p.bom.map(b=>`<div class="bom-line"><span>${material(b.material)?.name||'—'}</span><b>${b.qty} ${material(b.material)?.unit||''}/un</b></div>`).join('')}<h4>Operações / tempo</h4><div class="operation-list">${p.operations.map(op=>{const r=resource(op.resource);return `<div><span>${op.name}<small>${r?.name||'Sem recurso'} · ${r?.type==='manual'?'Manual':'Equipamento'}</small></span><b>${op.setupMin}m prep + ${op.runMin}m/${op.batchQty} un</b></div>`}).join('')}</div><div class="total-time">Exemplo 100 un: <b>${productMinutes(p,100)} min</b></div></div></article>`).join('')}</div>`;mats.innerHTML=`<div class="management-grid">${state.materials.map(m=>`<article class="manage-card"><span class="tag">MATÉRIA-PRIMA</span><h3>${m.name}</h3><div class="stock-big">${m.stock} <small>${m.unit}</small></div><p>Mínimo ${m.min} · ${money(m.cost)}/${m.unit}</p></article>`).join('')}</div>`;res.innerHTML=`<div class="management-grid">${state.resources.map(r=>`<article class="manage-card"><span class="tag">${r.type==='manual'?'MANUAL':'EQUIPAMENTO'}</span><h3>${r.name}</h3><p>${r.process}</p><div class="resource-spec"><span>${r.minutesDay} min/dia</span><span>Desgaste ${r.wear||0}%/h</span><span>Retorno ${r.returnMin||0} min</span></div></article>`).join('')}</div>`}
 function refreshClientProducts(){document.querySelectorAll('.client-item select').forEach(s=>{const current=s.value;s.innerHTML=options(state.products,current)})}
 function clientRow(){const p=state.products[0];return `<div class="client-item client-item-v2"><div class="client-product-choice"><select data-client-product>${options(state.products,p?.id)}</select><small data-client-name>${p?.name||'Produto'}</small></div><input data-client-qty type="number" min="1" value="100"><button type="button" data-client-remove>×</button></div>`}
 function setupClient(){const root=document.getElementById('clientItems'),add=document.getElementById('addClientItem'),check=document.getElementById('checkAvailability');if(!root||!add)return;root.innerHTML=clientRow();const bind=()=>{root.querySelectorAll('[data-client-remove]').forEach(b=>b.onclick=()=>{if(root.children.length>1)b.closest('.client-item').remove()});root.querySelectorAll('[data-client-product]').forEach(s=>s.onchange=()=>{s.parentElement.querySelector('[data-client-name]').textContent=product(s.value)?.name||''})};bind();add.onclick=()=>{root.insertAdjacentHTML('beforeend',clientRow());bind()};if(check)check.onclick=()=>{const rows=[...root.querySelectorAll('.client-item')].map(r=>({p:product(r.querySelector('[data-client-product]').value),qty:+r.querySelector('[data-client-qty]').value||1}));const prodMin=rows.reduce((s,r)=>s+productMinutes(r.p,r.qty),0);const workDays=Math.max(1,Math.ceil(prodMin/480));const desired=document.getElementById('clientDesiredDate')?.value;document.getElementById('clientAvailability').insertAdjacentHTML('beforeend',`<div class="availability-result success"><span>CÁLCULO PELO BOM</span><strong>${workDays} dia${workDays>1?'s':''} úteis de produção</strong><p>${rows.map(r=>`${r.qty}× ${r.p.name}`).join(' · ')}</p><small>${prodMin} minutos produtivos antes da margem de segurança e transporte.${desired?' Data desejada: '+desired:''}</small></div>`)} }
 document.getElementById('addMaterial')?.addEventListener('click',openMaterial);
 document.getElementById('addMachine')?.addEventListener('click',openResource);
 document.getElementById('addProduct')?.addEventListener('click',openProduct);
 renderCatalog();setupClient();
 window.BennieManufacturing={state,productMinutes,operationMinutes,unitMaterialCost,openProduct,openMaterial,openResource};
})();