(()=>{
 const $=id=>document.getElementById(id);let artUrl='',artName='',last=[];
 const mm={w:210,h:297};
 function inputs(){return{w:+$('nestW').value||50,h:+$('nestH').value||30,qty:Math.max(1,+$('nestQty').value||1),gap:Math.max(0,+$('nestGap').value||2),mx:Math.max(0,+$('safeX').value||14),my:Math.max(0,+$('safeY').value||18),rotate:$('nestRotate').checked}}
 function collides(x,y,w,h,p,g){return p.some(a=>!(x+w+g<=a.x||a.x+a.w+g<=x||y+h+g<=a.y||a.y+a.h+g<=y))}
 function pack(c){const W=mm.w-c.mx*2,H=mm.h-c.my*2,placed=[];for(let n=0;n<c.qty;n++){let best=null;const variants=c.rotate&&c.w!==c.h?[[c.w,c.h,false],[c.h,c.w,true]]:[[c.w,c.h,false]];for(const [w,h,rot] of variants){for(let y=0;y<=H-h+.001;y+=1){for(let x=0;x<=W-w+.001;x+=1){if(!collides(x,y,w,h,placed,c.gap)){const score=y*1000+x+(rot?.1:0);if(!best||score<best.score)best={x,y,w,h,rot,score};break}}if(best&&best.y===y)break}}if(!best)break;placed.push(best)}return{placed,W,H}}
 function render(){const c=inputs(),r=pack(c);last=r.placed;const safe=$('nestSafe'),paper=$('nestPaper');safe.style.left=(c.mx/mm.w*100)+'%';safe.style.top=(c.my/mm.h*100)+'%';safe.style.width=(r.W/mm.w*100)+'%';safe.style.height=(r.H/mm.h*100)+'%';safe.innerHTML=r.placed.map((a,i)=>`<div class="nest-item ${a.rot?'rot':''}" style="left:${a.x/r.W*100}%;top:${a.y/r.H*100}%;width:${a.w/r.W*100}%;height:${a.h/r.H*100}%">${artUrl?`<img src="${artUrl}" alt="">`:`<b>♡</b>`}<span>${i+1}</span></div>`).join('')+(r.placed.length?`<div class="nesting-empty" style="display:none"></div>`:`<div class="nesting-empty">A arte não cabe na área útil com estas medidas.</div>`);const area=r.W*r.H,used=r.placed.reduce((s,a)=>s+a.w*a.h,0),eff=area?used/area*100:0,sheets=Math.ceil(c.qty/Math.max(1,r.placed.length));$('nestPlaced').textContent=r.placed.length;$('nestEfficiency').textContent=eff.toFixed(1)+'%';$('nestSheets').textContent=sheets;$('nestWaste').textContent=(100-eff).toFixed(1)+'%';$('nestDetails').innerHTML=`<div><span>Área A4</span><b>210 × 297 mm</b></div><div><span>Área útil configurada</span><b>${r.W.toFixed(0)} × ${r.H.toFixed(0)} mm</b></div><div><span>Peça</span><b>${c.w} × ${c.h} mm</b></div><div><span>Separação</span><b>${c.gap} mm</b></div><div><span>Arquivo</span><b>${artName||'Demonstração'}</b></div>`}
 function init(){if(!$('nestPaper'))return;$('nestFile').onchange=e=>{const f=e.target.files?.[0];if(!f)return;if(!/image\/(png|svg\+xml)/.test(f.type)){alert('Use um arquivo PNG ou SVG.');return}if(artUrl)URL.revokeObjectURL(artUrl);artUrl=URL.createObjectURL(f);artName=f.name;render()};['nestW','nestH','nestQty','nestGap','safeX','safeY','nestRotate'].forEach(id=>$(id).addEventListener('input',render));$('runNesting').onclick=render;$('resetNesting').onclick=()=>{$('nestW').value=48;$('nestH').value=32;$('nestQty').value=30;$('nestGap').value=2;$('safeX').value=14;$('safeY').value=18;$('nestRotate').checked=true;render()};render()}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();