(()=>{
 const $=id=>document.getElementById(id);
 const A4={w:210,h:297},GRID=.8,ALPHA=22;
 let artUrl='',artName='',ratio=48/32,maskSource=null,editingDim=false;
 const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
 function cfg(){return{w:+$('nestW').value||48,h:+$('nestH').value||32,qty:Math.max(1,+$('nestQty').value||1),gap:Math.max(0,+$('nestGap').value||2),mx:Math.max(0,+$('safeX').value||14),my:Math.max(0,+$('safeY').value||18),rotate:$('nestRotate').checked}}
 function loadImage(url){return new Promise((res,rej)=>{const im=new Image();im.onload=()=>res(im);im.onerror=rej;im.src=url})}
 async function buildSourceMask(){if(!artUrl){maskSource=null;return}const im=await loadImage(artUrl),max=180,scale=Math.min(1,max/Math.max(im.naturalWidth||im.width,im.naturalHeight||im.height)),cw=Math.max(8,Math.round((im.naturalWidth||im.width)*scale)),ch=Math.max(8,Math.round((im.naturalHeight||im.height)*scale)),cv=document.createElement('canvas');cv.width=cw;cv.height=ch;const ctx=cv.getContext('2d',{willReadFrequently:true});ctx.clearRect(0,0,cw,ch);ctx.drawImage(im,0,0,cw,ch);const d=ctx.getImageData(0,0,cw,ch),pix=d.data;let minX=cw,minY=ch,maxX=-1,maxY=-1;for(let y=0;y<ch;y++)for(let x=0;x<cw;x++){if(pix[(y*cw+x)*4+3]>ALPHA){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y)}}if(maxX<0){maskSource=null;return}const w=maxX-minX+1,h=maxY-minY+1,crop=new Uint8Array(w*h);for(let y=0;y<h;y++)for(let x=0;x<w;x++)crop[y*w+x]=pix[((y+minY)*cw+(x+minX))*4+3]>ALPHA?1:0;maskSource={w,h,data:crop};ratio=w/h;$('nestW').value=(+$('nestH').value*ratio).toFixed(1)}
 function rotateMask(src,q){q=((q%4)+4)%4;if(!q)return src;let cur=src;for(let k=0;k<q;k++){const out=new Uint8Array(cur.w*cur.h);const nw=cur.h,nh=cur.w;for(let y=0;y<cur.h;y++)for(let x=0;x<cur.w;x++)out[x*nw+(nw-1-y)]=cur.data[y*cur.w+x];cur={w:nw,h:nh,data:out}}return cur}
 function scaleMask(src,wMm,hMm,gapMm){const gw=Math.max(1,Math.ceil(wMm/GRID)),gh=Math.max(1,Math.ceil(hMm/GRID)),raw=new Uint8Array(gw*gh);for(let y=0;y<gh;y++)for(let x=0;x<gw;x++){const sx=Math.min(src.w-1,Math.floor(x/gw*src.w)),sy=Math.min(src.h-1,Math.floor(y/gh*src.h));raw[y*gw+x]=src.data[sy*src.w+sx]}const r=Math.ceil((gapMm/2)/GRID);if(!r)return{w:gw,h:gh,data:raw,visual:raw};const out=new Uint8Array(gw*gh);for(let y=0;y<gh;y++)for(let x=0;x<gw;x++)if(raw[y*gw+x])for(let dy=-r;dy<=r;dy++)for(let dx=-r;dx<=r;dx++){if(dx*dx+dy*dy>r*r)continue;const nx=x+dx,ny=y+dy;if(nx>=0&&(nx<gw)&&ny>=0&&ny<gh)out[ny*gw+nx]=1}return{w:gw,h:gh,data:out,visual:raw}}
 function cells(mask){const a=[];for(let y=0;y<mask.h;y++)for(let x=0;x<mask.w;x++)if(mask.data[y*mask.w+x])a.push([x,y]);return a}
 function fits(occ,W,H,m,x0,y0,cs){if(x0<0||y0<0||x0+m.w>W||y0+m.h>H)return false;for(const [x,y] of cs)if(occ[(y0+y)*W+x0+x])return false;return true}
 function stamp(occ,W,m,x0,y0,cs){for(const [x,y] of cs)occ[(y0+y)*W+x0+x]=1}
 function makeVariants(c){const source=maskSource||{w:100,h:Math.max(1,Math.round(100/ratio)),data:new Uint8Array(100*Math.max(1,Math.round(100/ratio))).fill(1)},angles=c.rotate?[0,1,2,3]:[0];return angles.map(q=>{const src=rotateMask(source,q),rot=q%2===1,w=rot?c.h:c.w,h=rot?c.w:c.h,m=scaleMask(src,w,h,c.gap);return{q,rot,w,h,m,cs:cells(m)}})}
 function tryPack(c,mode){const W=Math.floor((A4.w-c.mx*2)/GRID),H=Math.floor((A4.h-c.my*2)/GRID),occ=new Uint8Array(W*H),vars=makeVariants(c),placed=[];for(let n=0;n<c.qty;n++){let best=null;for(const v of vars){const ys=mode===1?[...Array(Math.max(0,H-v.m.h+1)).keys()].reverse():[...Array(Math.max(0,H-v.m.h+1)).keys()];for(const y of ys){const xs=mode===2?[...Array(Math.max(0,W-v.m.w+1)).keys()].reverse():[...Array(Math.max(0,W-v.m.w+1)).keys()];for(const x of xs){if(!fits(occ,W,H,v.m,x,y,v.cs))continue;const score=(mode===2?W-x:x)+(mode===1?H-y:y)*1.07;if(!best||score<best.score)best={x,y,v,score};break}if(best&&Math.abs(best.y-y)<1)break}}if(!best)break;stamp(occ,W,best.v.m,best.x,best.y,best.v.cs);placed.push({x:best.x*GRID,y:best.y*GRID,w:best.v.w,h:best.v.h,rot:best.v.rot,q:best.v.q})}return{placed,W:W*GRID,H:H*GRID}}
 function pack(c){let best=null;for(let mode=0;mode<3;mode++){const r=tryPack(c,mode);if(!best||r.placed.length>best.placed.length)best=r}return best}
 function render(){const c=cfg(),r=pack(c),safe=$('nestSafe');safe.style.left=(c.mx/A4.w*100)+'%';safe.style.top=(c.my/A4.h*100)+'%';safe.style.width=(r.W/A4.w*100)+'%';safe.style.height=(r.H/A4.h*100)+'%';safe.innerHTML=r.placed.map((a,i)=>`<div class="nest-item ${a.rot?'rot':''}" style="left:${a.x/r.W*100}%;top:${a.y/r.H*100}%;width:${a.w/r.W*100}%;height:${a.h/r.H*100}%">${artUrl?`<img src="${artUrl}" alt="">`:'<b>♡</b>'}<span>${i+1}</span></div>`).join('')+(r.placed.length?'':`<div class="nesting-empty">A arte não cabe na área útil com estas medidas.</div>`);const safeArea=r.W*r.H,pieceArea=c.w*c.h,eff=safeArea?Math.min(100,r.placed.length*pieceArea/safeArea*100):0,sheets=Math.ceil(c.qty/Math.max(1,r.placed.length));$('nestPlaced').textContent=r.placed.length;$('nestEfficiency').textContent=eff.toFixed(1)+'%';$('nestSheets').textContent=sheets;$('nestWaste').textContent=(100-eff).toFixed(1)+'%';$('nestDetails').innerHTML=`<div><span>Área útil</span><b>${r.W.toFixed(1)} × ${r.H.toFixed(1)} mm</b></div><div><span>Peça proporcional</span><b>${c.w.toFixed(1)} × ${c.h.toFixed(1)} mm</b></div><div><span>Máscara</span><b>${maskSource?'Contorno alfa real':'Retângulo demonstrativo'}</b></div><div><span>Rotações testadas</span><b>${c.rotate?'0°, 90°, 180°, 270°':'0°'}</b></div><div><span>Arquivo</span><b>${artName||'Demonstração'}</b></div>`}
 function lockRatio(){const w=$('nestW'),h=$('nestH');w.addEventListener('input',()=>{if(editingDim)return;editingDim=true;h.value=(+w.value/ratio).toFixed(1);editingDim=false;render()});h.addEventListener('input',()=>{if(editingDim)return;editingDim=true;w.value=(+h.value*ratio).toFixed(1);editingDim=false;render()})}
 async function init(){if(!$('nestPaper'))return;lockRatio();$('nestFile').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;if(!/image\/(png|svg\+xml)/.test(f.type)){alert('Use um arquivo PNG ou SVG.');return}if(artUrl)URL.revokeObjectURL(artUrl);artUrl=URL.createObjectURL(f);artName=f.name;await buildSourceMask();render()};['nestQty','nestGap','safeX','safeY','nestRotate'].forEach(id=>$(id).addEventListener('input',render));$('runNesting').onclick=render;$('resetNesting').onclick=()=>{$('nestW').value=48;$('nestH').value=(48/ratio).toFixed(1);$('nestQty').value=30;$('nestGap').value=2;$('safeX').value=14;$('safeY').value=18;$('nestRotate').checked=true;render()};render()}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();